# Generated by Django 4.0.2 on 2022-02-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testfield', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='DropBox',
        ),
    ]
