# Generated by Django 4.0.2 on 2022-02-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s3api', '0003_uploadedfile_delete_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
