# Generated by Django 4.0.2 on 2022-02-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s3api', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DropBox',
        ),
    ]
