# Generated by Django 4.0.2 on 2022-02-14 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdb', '0002_img_imgfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='imgFile',
        ),
    ]
