# Generated by Django 4.0.2 on 2022-02-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdb', '0004_alter_img_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='imgUrl',
            field=models.FileField(upload_to='%y/%m/%d'),
        ),
    ]
